### ISSUE TITLE
【Develop】cppsharpを用いたC++コードのC#へのバインド

### ISSUE THREAD

**Issue by YuukiReiya** [YuukiReiya/Template-OnlineProject#88]

**Comment by YuukiReiya** [comment]
>今回はCppSharpが使えそうだと思ったのでリポジトリ用意して検証しつつ組み込んでみる。

リポジトリのリンクは[こちら](https://github.com/YuukiReiya/CppSharp_NativeBind)
※PrivateRepository

**Comment by YuukiReiya** [comment]
![err_!](https://user-images.githubusercontent.com/37837548/208269452-b3f4f525-8b93-4b62-b305-9590aecbc934.png)
メソッドを呼び出そうとした際に出たエラー。
```
System.BadImageFormatException:
間違ったフォーマットのプログラムを読み込もうとしました。 (0x8007000B)
   at Cpp.Foo.__Internal.FooAdd(IntPtr foo)
   at Cpp.Foo.FooAdd(Foo foo) in C:\Users\yuki\Documents\develop\T\CppSharp_NativeBind\Project\Software\Software\scripts\external\Cpp.cs:line 115
   at CSharp.Program.Main(String[] args) in C:\Users\yuki\Documents\develop\T\CppSharp_NativeBind\Project\Software\Software\scripts\common\Program.cs:line 23
```

**Comment by YuukiReiya** [comment]
![image](https://user-images.githubusercontent.com/37837548/208282476-63e14b62-7ba8-4947-8169-f38d2afa482d.png)

生成されたコードはunsafeらしいので`アンセーフコードの許可`をする

![unsafe_ok](https://user-images.githubusercontent.com/37837548/208282516-82f5f4bf-48d8-4f78-a57c-67b52a2ff21b.png)
