### ISSUE TITLE
【開発】暗黙リンクのあるC++NativePluginのUnityClient上での動作を担保

### ISSUE THREAD

**Issue by YuukiReiya** [YuukiReiya/Template-OnlineProject#90]

**Comment by YuukiReiya** [comment]
※dumpbin 使え！みたいな記事も見つけて実行してみたが依存関係は分からなかった。

出力(暗黙リンク有り:lua)
```
Microsoft (R) COFF/PE Dumper Version 14.00.24245.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file <パス>\Client\Assets\Plugins\NativePlugins\ExternalDynamicLinkLibrary.dll

File Type: DLL

  Summary

        1000 .00cfg
        1000 .data
        2000 .idata
        1000 .msvcjmc
        3000 .pdata
        5000 .rdata
        1000 .reloc
        1000 .rsrc
        D000 .text
       10000 .textbss

```
出力(暗黙リンク無し:動作するやつ)
```
Dump of file <パス>\Client\Assets\Plugins\NativePlugins\UnityDLLforCPP.dll

File Type: DLL

  Summary

        1000 .00cfg
        1000 .data
        1000 .idata
        1000 .msvcjmc
        3000 .pdata
        3000 .rdata
        1000 .reloc
        1000 .rsrc
        8000 .text
       10000 .textbss
```

**Comment by YuukiReiya** [comment]
DLLのホットリロードに関して[PatchLibrary](https://github.com/i-saint/PatchLibrary)という選択肢もあるらしい。
参考:https://tips.hecomi.com/entry/2017/01/28/163155

**Comment by YuukiReiya** [comment]
このあたりも参考になりそうなのでリンクを貼っとく。
https://m-kawanon.hatenadiary.org/entry/20110731/1312116123

**Comment by YuukiReiya** [comment]
```cs
//------------------------------------------------------------------------------------------------------------------------------------------
// エラーコード
//------------------------------------------------------------------------------------------------------------------------------------------
            var create = lpFile.GetDelegate<TLUA_PTR>($"edllua_create");
            var instance = create();
            var initialize = lpFile.GetDelegate<TLUA_DEFAULT>($"edllua_initialize");
            // 初期化.
            initialize(instance);
            // ロード.
            var load = lpFile.GetDelegate<TLUA_LOAD>($"edllua_load");
//------------------------------------------------------------------------------------------------------------------------------------------
// 補足
// delegate IntPtr TLUA_PTR();
// delegate void TLUA_DEFAULT(IntPtr _);
// delegate bool TLUA_LOAD(IntPtr _, string __);
//------------------------------------------------------------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------------------------
// エラー内容
//------------------------------------------------------------------------------------------------------------------------------------------
External component has thrown an exception.
   at Program.f2() in [パス]\dll_dev_sample\dll_dev_sample\Program.cs:line 93
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Program.f2()
   at Program.execute()
   at Program.Main(System.String[])
```
ここまでやって読み込めなかったという罠。
TODOとして今後に課題を残しつつ、`xLua`がMITなので利用した方が早いという結論へ。
※UnityCLで利用するまでもなく、C#コンソールアプリケーションでしくった。(Unity未検証、恐らくクラッシュする)

---

# TODO

`AccessViolationException`の問題の特定と利用できるようにする。

**Comment by YuukiReiya** [comment]
>「LNK1104 '*.lib'を開くことが出来ません。」

↑の対策として
`DLL`から`lib`ファイルの生成方法。
https://qiita.com/iwatake2222/items/3caf294726918c3af9e6
